name: Test Docker image

on:
  pull_request:
    branches: [ main* ]
  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}-docker-test
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  test:
    uses: OmniTrustILM/.github/.github/workflows/containers-test.yml@main
    secrets: inherit
    with:
      image: ilm/scheduler
      cache-scope: scheduler
      build-args: |
        VERSION=${{ github.ref_name }}
